 <div class="alert alert-block alert-info" style="margin-top: 20px">
 <a href="http://cocl.us/NotebooksPython101"><img src = "https://ibm.box.com/shared/static/yfe6h4az47ktg2mm9h05wby2n7e8kei3.png" width = 750, align = "center"></a>




<a href="https://www.bigdatauniversity.com"><img src = "https://ibm.box.com/shared/static/ugcqz6ohbvff804xp84y4kqnvvk3bq1g.png" width = 300, align = "center"></a>



<h1 align=center><font size = 5>Two-Dimensional Tensors </font></h1>

Import these libraries:

In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import torch
import pandas as pd

Consider the list <strong>a</strong>; the list contains three nested lists <strong>each of equal size</strong>. 

In [2]:
a=[[11,12,13],[21,22,23],[31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

Cast the list to a tensor:

In [3]:
#every elment if of the same type 
A=torch.tensor(a)
A

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

Use the method **ndimension** to obtain the number of axes or dimensions referred to as the rank. 

In [4]:
A.ndimension()

2

The attribute **shape** returns the size or number of each dimension.

In [5]:
A.shape

torch.Size([3, 3])

The total number of elements in the tensor is given by the attribute **size**.

In [6]:
A.size()

torch.Size([3, 3])

Convert a tensor to a numpy array: 

In [7]:
A.numpy()

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

Convert a 2D  numpy array to a tensor: 

In [8]:
numpy_array=np.array([[1.1,1.2],[1.1,1.2]])

torch_tensor =torch.from_numpy(numpy_array)

torch_tensor

tensor([[1.1000, 1.2000],
        [1.1000, 1.2000]], dtype=torch.float64)

Convert a Pandas DataFrame to a tensor: 

In [9]:
df=pd.DataFrame({'a':[11,21,31],'b':[12,22,312]})
df.head()

a    b
0  11   12
1  21   22
2  31  312

Convert from Pandas to torch: 

In [10]:
pandas_to_torch=torch.from_numpy(df.values)
pandas_to_torch

tensor([[ 11,  12],
        [ 21,  22],
        [ 31, 312]])

### Accessing different elements of a Tensor

You can use rectangular brackets to access the different elements of the tensor. The correspondence  between the rectangular brackets and the list and the rectangular representation is shown in the following figure for a 3x3 tensor:  

 <a><img src = "https://ibm.box.com/shared/static/dsa3nfspbvarlwikt2nuva4ka8ez7stm.png" width = 500, align = "center"></a>


You can access the 2nd-row 3rd column as shown in the following figure:

 <a><img src="https://ibm.box.com/shared/static/7ezznbkz63cvd39wn6yidqojdqbh9v0u.png" width=500 align="center"> </a>

You simply use the square brackets and the indices corresponding to the element that you want:

In [11]:
A[1,2]

tensor(23)

You can also use the following notation to obtain the elements: 

In [12]:
A[1][2]

tensor(23)

Consider the elements shown in the following figure: 

 <a><img src="https://ibm.box.com/shared/static/178texrln4qv2figweqtmgliwwikncnd.png" width=500 align="center"> </a>

Access the element: 

In [13]:
A[0][0]

tensor(11)

You can also use slicing in tensor. Consider the following figure. You want to obtain the first two columns in the first row:  

 <a><img src="https://ibm.box.com/shared/static/mjmlvk9d9p1fokh5e1ka51bayw8qnv1e.png" width=500 align="center"> </a>

This can be done with the following syntax: 

In [14]:
A[0][0:2]

tensor([11, 12])

Similarly, you can obtain the first two rows of the 3rd column:

In [15]:
A[1:3,2]

tensor([23, 33])

This corresponds to the following figure: 

<a><img src="https://ibm.box.com/shared/static/p9y7q111sq4epvkn2vtvkda5667gyiho.png" width=500 align="center" ></a>

# Basic Operations 

You can also add tensors; the process is identical to matrix addition. Matrix addition of <strong>X</strong> and <strong>Y</strong> is shown in the following figure:

 <a><img src="https://ibm.box.com/shared/static/6fiwxq3nsnpk3ae82t0vbxv8qtz1c1gs.png" width=500 align="center"> </a>

The tensors are given by <strong>X</strong> and <strong>Y</strong>:

In [16]:
X=torch.tensor([[1,0],[0,1]]) 
X

tensor([[1, 0],
        [0, 1]])

In [17]:
Y=torch.tensor([[2,1],[1,2]]) 
Y

tensor([[2, 1],
        [1, 2]])

Add the tensors:

In [18]:
Z=X+Y
Z

tensor([[3, 1],
        [1, 3]])

Multiplying a tensor by a scaler is identical to multiplying a matrix by a scaler. If you multiply the matrix **Y** by the scaler 2, you simply multiply every element in the matrix by 2 as shown in the figure:

 <a><img src="https://ibm.box.com/shared/static/b942bzigx47l3bfkielh0d36ghurrma8.png" width=500 align="center"> </a>

Perform the same operation with a tensor: 

In [19]:
Y=torch.tensor([[2,1],[1,2]]) 
Y

tensor([[2, 1],
        [1, 2]])

In [20]:
Z=2*Y
Z

tensor([[4, 2],
        [2, 4]])

Multiplication of two tensors corresponds to an element-wise product or  Hadamard product.  Consider matrix  <strong>X</strong> and <strong>Y</strong>. The Hadamard product corresponds to multiplying each of the elements in the same position, that is, multiplying elements contained in the same color boxes together. The result is a new matrix that is the same size as matrix <strong>Y</strong> or <strong>X</strong> as shown in the following figure:

 <a><img src="https://ibm.box.com/shared/static/7yha01bj0orozx9vicpf32p6p4t3f3ii.png" width=500 align="center"> </a>


Perform element-wise product of the tensor <strong>X</strong> and <strong>Y</strong>:

In [21]:
Y=torch.tensor([[2,1],[1,2]]) 
Y

tensor([[2, 1],
        [1, 2]])

In [22]:
X=torch.tensor([[1,0],[0,1]]) 
X

tensor([[1, 0],
        [0, 1]])

In [23]:
Z=X*Y
Z

tensor([[2, 0],
        [0, 2]])

Perform matrix multiplication with the tensors <strong>A</strong> and <strong>B</strong>:

First, define tensor <strong>A</strong> and <strong>B</strong>:

In [24]:
A=torch.tensor([[0,1,1],[1,0,1]])
A

tensor([[0, 1, 1],
        [1, 0, 1]])

In [25]:
B=torch.tensor([[1,1],[1,1],[-1,1]])
B

tensor([[ 1,  1],
        [ 1,  1],
        [-1,  1]])

Use the torch function **mm** to multiply the tensors together:

In [26]:
Z=torch.mm(A,B)
Z

tensor([[0, 2],
        [0, 2]])

Apply functions in an element-wise: 

In [27]:
torch.sin(Z.type(torch.double))

tensor([[0.0000, 0.9093],
        [0.0000, 0.9093]], dtype=torch.float64)

<a href="http://cocl.us/NotebooksPython101bottom"><img src = "https://ibm.box.com/shared/static/irypdxea2q4th88zu1o1tsd06dya10go.png" width = 750, align = "center"></a>



#### About the Authors:  

 [Joseph Santarcangelo]( https://www.linkedin.com/in/joseph-s-50398b136/) has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

Other contributors: [Michelle Carey](  https://www.linkedin.com/in/michelleccarey/),[Mavis Zhou ]( www.linkedin.com/in/jiahui-mavis-zhou-a4537814a) 

Copyright &copy; 2018 [cognitiveclass.ai](cognitiveclass.ai?utm_source=bducopyrightlink&utm_medium=dswb&utm_campaign=bdu). This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license/).​

In [29]:
a = [[1,2,3],[0,1,0]]
a[1][0:2]

[0, 1]

In [ ]:
aa