<div class="alert alert-block alert-info" style="margin-top: 20px">
 <a href="http://cocl.us/pytorch_link_top"><img src = "http://cocl.us/Pytorch_top" width = 950, align = "center"></a>

<img src = "https://ibm.box.com/shared/static/ugcqz6ohbvff804xp84y4kqnvvk3bq1g.png" width = 200, align = "center">



<h1 align=center><font size = 5>Linear regression 1-D: Prediction</font></h1> 

# Table of Contents
In this lab, we will  review how to make a prediction in several different ways by using Pytorch. 

<div class="alert alert-block alert-info" style="margin-top: 20px">
<li><a href="#ref0">Prediction  </a></li>
<li><a href="#ref1">Class Linear   </a></li>
<li><a href="#ref2">Build Custom Modules </a></li>

<br>
<p></p>
Estimated Time Needed: <strong>15 min</strong>
</div>

<hr>

<a id="ref0"></a>
<h2 align=center>Prediction</h2>

Import all the necessary modules. 

In [1]:
import torch

Create the following expression:

 <img src = "https://ibm.box.com/shared/static/ky0n1mgs378dgw47pmhnqm35mw737fmv.png" width = 200, align = "center"></a>

Define the parameters:

In [2]:
w=torch.tensor(2.0,requires_grad=True)
b=torch.tensor(-1.0,requires_grad=True)

The function forward makes the prediction: 

In [3]:
def forward(x):
    yhat=w*x+b
    return yhat

Let's make the following prediction 

<img src = "https://ibm.box.com/shared/static/keqeopewwwezt09ofpuw17niw0jouock.png" width = 200, align = "center"></a>

In [4]:
x=torch.tensor([[1.0]])
yhat=forward(x)
yhat

tensor([[1.]], grad_fn=<ThAddBackward>)

You can predict for multiple inputs:

<img src = "https://ibm.box.com/shared/static/l0y4ahfs66e8jsz0fhw6e8kbxa1qxng1.png" width =500, align = "center"></a>

For example, consider the following tensor; each row corresponds to a sample: 

In [5]:
x=torch.tensor([[1.0],[2.0]])

You can get the shape of the tensor:

In [6]:
x.shape

torch.Size([2, 1])

Now make a prediction: 

In [7]:
yhat=forward(x)
yhat

tensor([[1.],
        [3.]], grad_fn=<ThAddBackward>)

In [8]:
yhat

tensor([[1.],
        [3.]], grad_fn=<ThAddBackward>)

#### Cast the following nested list to a tensor and make a prediction:

In [10]:
x=torch.tensor([[1.0],[2.0],[3.0]])
yhat=forward(x)
yhat

tensor([[1.],
        [3.],
        [5.]], grad_fn=<ThAddBackward>)



Double-click __here__ for the solution.

<!-- Your answer is below:
x=torch.tensor([[1.0],[2.0],[3.0]])
yhat=forward(x)
yhat

-->


<a id="ref1"></a>
<h2 align=center>Class Linear  </h2>

The linear class can be used to make a prediction. You'll also use the linear class to build more complex models. Import the module:

In [11]:
from torch.nn import Linear
import torch

Set the random seed because the parameters are randomly initialized:

In [12]:
torch.manual_seed(1)

Create the object by using the constructor: 

In [20]:
lr=Linear(in_features=1,out_features=1,bias=True)

Review the model parameters: 

In [21]:
print(list(lr.parameters()))

[Parameter containing:
tensor([[-0.2057]], requires_grad=True), Parameter containing:
tensor([0.5087], requires_grad=True)]


This is equivalent to the following expression:  

<img src = "https://ibm.box.com/shared/static/tpi322ljownbhiq114dmo66yxi8sn2tl.png" width =200, align = "center"></a>

Make a single prediction: 

In [22]:
x=torch.tensor([[1.0]])
yhat=lr(x)
yhat

tensor([[0.3030]], grad_fn=<ThAddmmBackward>)

Similarly, you can make multiple predictions:

<img src = "https://ibm.box.com/shared/static/74rixlo4np50n7qkimffje9do8aco3hd.png" width =500, align = "center"></a>

It's just like using the function forward: 

In [23]:
x=torch.tensor([[1.0],[2.0]])
yhat=lr(x)
yhat

tensor([[0.3030],
        [0.0973]], grad_fn=<ThAddmmBackward>)

#### Cast the following nested list to a tensor and make a prediction by using the object lr:

In [25]:
x=torch.tensor([[1.0],[2.0],[3.0]])
yhat=lr(x)
yhat

tensor([[ 0.3030],
        [ 0.0973],
        [-0.1084]], grad_fn=<ThAddmmBackward>)


Double-click __here__ for the solution.

<!-- Your answer is below:
x=torch.tensor([[1.0],[2.0],[3.0]])
yhat=lr(x)
yhat

-->

<a id="ref2"></a>
<h2 align=center>Build Custom Modules </h2>

Now, let's build a custom module. You can make more complex models by using this method later on. 

In [26]:
from torch import nn

Define the class: 

In [27]:
class LR(nn.Module):
    def __init__(self,input_size,output_size):
        super(LR,self).__init__()
        self.linear=nn.Linear(input_size,output_size)
    def forward(self,x):
        out=self.linear(x)
        return out

Create an object by using the constructor: 

In [28]:
lr=LR(1,1)

Review the model parameters:

In [29]:
print(list(lr.parameters()))

[Parameter containing:
tensor([[0.1390]], requires_grad=True), Parameter containing:
tensor([-0.1224], requires_grad=True)]


In [30]:
lr.linear

Linear(in_features=1, out_features=1, bias=True)

Make single or multiple predictions: 

In [31]:
x=torch.tensor([[1.0]])
yhat=lr(x)

In [32]:
x=torch.tensor([[1.0],[2.0]])
yhat=lr(x)
yhat

tensor([[0.0166],
        [0.1556]], grad_fn=<ThAddmmBackward>)

Create an object <code>lr1</code> from your Module and make a prediction by using the following tensor: 

In [34]:
lr1=LR(1,1)
x=torch.tensor([[1.0],[2.0],[3.0]])
yhat=lr1(x)
yhat

tensor([[-0.0245],
        [ 0.3408],
        [ 0.7060]], grad_fn=<ThAddmmBackward>)


Double-click __here__ for the solution.
<!-- Your answer is below:
x=torch.tensor([[1.0],[2.0],[3.0]])
lr1=LR(1,1)
yhat=lr(x)
yhat

-->

 <!-- Your answer is below:
x=torch.tensor([[1.0],[2.0],[3.0]])
lr1=LR(1,1)
yhat=lr1(x)
yhat
-->

<div class="alert alert-block alert-info" style="margin-top: 20px">
 <a href="http://cocl.us/pytorch_link_bottom"><img src = "http://cocl.us/pytorch_image_bottom" width = 950, align = "center"></a>

# About the Authors:  

 [Joseph Santarcangelo]( https://www.linkedin.com/in/joseph-s-50398b136/) has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.
 

Other contributors: [Michelle Carey](  https://www.linkedin.com/in/michelleccarey/), [Mavis Zhou](  https://www.linkedin.com/in/jiahui-mavis-zhou-a4537814a/) 

<hr>

Copyright &copy; 2018 [cognitiveclass.ai](cognitiveclass.ai?utm_source=bducopyrightlink&utm_medium=dswb&utm_campaign=bdu). This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license/).